spring:
  application:
    name: TPO_04
  h2:
    console:
      path: /console
  datasource:
    url: jdbc:h2:mem:books
    username: jasper
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql/user.sql,classpath:sql/blog.sql,classpath:sql/Article.sql,classpath:sql/role.sql,classpath:sql/role_user.sql