INSERT INTO ARTICLE (TITLE,AUTHOR_ID,BLOG_ID) values
                                        ('article_1',1,1),
                                        ('article 2',2,1),
                                        ('article 3',1,2),
                                        ('article 4',3,3),
                                        ('article 5',4,4),
                                        ('article 6',5,2),
                                        ('article 7',4,5),
                                        ('article 8',7,7),
                                        ('article 9',8,8),
                                        ('article 10',9,9),
                                        ('article 11',10,10),
                                        ('article 12',11,11),
                                        ('article 13',12,12),
                                        ('article 14',13,13),
                                        ('article 15',14,14),
                                        ('article 16',15,15),
                                        ('article 17',16,16),
                                        ('article 18',17,17),
                                        ('article 19',18,18),
                                        ('article 20',19,19),
                                        ('article 21',10,1);